### ISSUE TITLE
Create Code Journal React-App from JS-Orign

### ISSUE THREAD

**Issue by j-alejandro-araujo** [j-alejandro-araujo/code-journal-react#1]
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create React-App
- [x] Move JS Code Journal files to Orig folder for reference.
- [x] Convert the **Create Entry page** , referencing main.js and index.html.
  - [x] Create the HTML skeleton and make sure it matches the original.
  - [x] Create Title, Photo, Notes, and Image input fields.
  - [ ] Implement local storage functionality.
  - [ ] Implement save functionality, once user clicks save, view switches to Entries page.
  - [ ] Make sure it saves to local storage.
